version: 2.1
jobs:
 build:
   docker:
     -image: circleci/node:current
   steps:
     - checkout
     - run: 
       name:install npm dependencies
       command: | 
       npm install  --save
    -run:
     name: Run tests
     command: |
       npm run test
workflows:
  version: 2
  build_and_test::
    jobs:
      - build
